export const fieldTypes = [
  "Address",
  "AutoComplete",
  "Checkbox",
  "Currency",
  "Date",
  "DateTime",
  "Decimal",
  "Dropdown",
  "Email",
  "Integer",
  "Location",
  "ReferenceValues",
  "DataReferenceSingle",
  "DataReferenceMulti",
  "CaseReferenceSingle",
  "CaseReferenceMulti",
  "Percentage",
  "Phone",
  "RadioButtons",
  "RichText",
  "Status",
  "Text",
  "TextArea",
  "Time",
  "URL",
  "UserReference",
] as const;

export type FieldType = (typeof fieldTypes)[number];
