import { Field } from "../types";

interface StepFields {
  [key: string]: {
    fields: Partial<Field>[];
  };
}

export const stepFields: StepFields = {
  "Design Details": {
    fields: [
      {
        name: "projectAddress",
        type: "Address",
        primary: true,
        required: true,
        label: "Project Address",
        description: "The address where the home will be built",
        order: 1,
      },
      {
        name: "squareFootage",
        type: "Text",
        primary: false,
        required: true,
        label: "Square Footage",
        description: "Total square footage of the home",
        order: 2,
      },
      {
        name: "numberOfBedrooms",
        type: "Text",
        primary: false,
        required: true,
        label: "Number of Bedrooms",
        description: "Total number of bedrooms",
        order: 3,
      },
      {
        name: "numberOfBathrooms",
        type: "Text",
        primary: false,
        required: true,
        label: "Number of Bathrooms",
        description: "Total number of bathrooms",
        order: 4,
      },
      {
        name: "floorPlan",
        type: "Text",
        primary: false,
        required: true,
        label: "Floor Plan",
        description: "Description of the floor plan layout",
        order: 5,
      },
    ],
  },
  "Select Materials": {
    fields: [
      {
        name: "exteriorMaterial",
        type: "Text",
        primary: false,
        required: true,
        label: "Exterior Material",
        description: "Primary material for exterior walls",
        order: 1,
      },
      {
        name: "roofingMaterial",
        type: "Text",
        primary: false,
        required: true,
        label: "Roofing Material",
        description: "Material for the roof",
        order: 2,
      },
      {
        name: "flooringMaterial",
        type: "Text",
        primary: false,
        required: true,
        label: "Flooring Material",
        description: "Material for the floors",
        order: 3,
      },
      {
        name: "windowType",
        type: "Text",
        primary: false,
        required: true,
        label: "Window Type",
        description: "Type of windows to be installed",
        order: 4,
      },
    ],
  },
  "Apply for Permit": {
    fields: [
      {
        name: "permitType",
        type: "Text",
        primary: false,
        required: true,
        label: "Permit Type",
        description: "Type of permit being applied for",
        order: 1,
      },
      {
        name: "applicationDate",
        type: "Date",
        primary: false,
        required: true,
        label: "Application Date",
        description: "Date of permit application",
        order: 2,
      },
      {
        name: "estimatedCost",
        type: "Currency",
        primary: false,
        required: true,
        label: "Estimated Cost",
        description: "Estimated cost of construction",
        order: 3,
      },
    ],
  },
  "Conduct Rough Inspection": {
    fields: [
      {
        name: "inspectionDate",
        type: "Date",
        primary: false,
        required: true,
        label: "Inspection Date",
        description: "Date of the rough inspection",
        order: 1,
      },
      {
        name: "inspectorName",
        type: "Text",
        primary: false,
        required: true,
        label: "Inspector Name",
        description: "Name of the inspector",
        order: 2,
      },
      {
        name: "inspectionNotes",
        type: "Text",
        primary: false,
        required: true,
        label: "Inspection Notes",
        description: "Notes from the rough inspection",
        order: 3,
      },
    ],
  },
  "Conduct Final Inspection": {
    fields: [
      {
        name: "inspectionDate",
        type: "Date",
        primary: false,
        required: true,
        label: "Inspection Date",
        description: "Date of the final inspection",
        order: 1,
      },
      {
        name: "inspectorName",
        type: "Text",
        primary: false,
        required: true,
        label: "Inspector Name",
        description: "Name of the inspector",
        order: 2,
      },
      {
        name: "inspectionNotes",
        type: "Text",
        primary: false,
        required: true,
        label: "Inspection Notes",
        description: "Notes from the final inspection",
        order: 3,
      },
      {
        name: "completionStatus",
        type: "Status",
        primary: false,
        required: true,
        label: "Completion Status",
        description: "Status of the final inspection",
        order: 4,
      },
    ],
  },
  "Complete Handover": {
    fields: [
      {
        name: "handoverDate",
        type: "Date",
        primary: false,
        required: true,
        label: "Handover Date",
        description: "Date of the handover",
        order: 1,
      },
      {
        name: "ownerName",
        type: "Text",
        primary: false,
        required: true,
        label: "Owner Name",
        description: "Name of the property owner",
        order: 2,
      },
      {
        name: "handoverNotes",
        type: "Text",
        primary: false,
        required: true,
        label: "Handover Notes",
        description: "Notes from the handover process",
        order: 3,
      },
      {
        name: "warrantyInfo",
        type: "Text",
        primary: false,
        required: true,
        label: "Warranty Information",
        description: "Warranty details provided to the owner",
        order: 4,
      },
    ],
  },
};
